#! /bin/bash
docker run -it -e DISPLAY=$DISPLAY -v $HOME/docker/platonics_data:/root/catkin_ws/src/platonics_dataset --privileged --network host \
  -v /opt/ros/noetic:/opt/ros/noetic \
  -v /path/to/libfranka:/path/to/libfranka \
  platonics_ros:latest
